- name: Install Nginx on slave1
  hosts: slave1
  become: true
  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

- name: Install Apache2 on slave2
  hosts: slave2
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes



