- name: Install docker on slave1
  hosts: slave1
  become: true
  tasks:
    - name: Installing docker
      apt:
        name: docker.io
        state: latest
        update_cache: yes

- name: Install docker on slave2
  hosts: slave2
  become: true
  tasks:
    - name: Install docker.io
      apt:
        name: docker.io
        state: latest
        update_cache: yes



